bux-server:
  enabled: true
  ingressControllers:
    - alb

pulse:
  enabled: true
  ingressControllers:
    - alb

bux-console:
  enabled: true
  ingressControllers:
    - alb

bux-wallet:
  enabled: true
  ingressControllers:
    - alb

global:
  domainName: test.domain
  certificate_arn: arn:aws:acm:us-east-1:123456789012:certificate/296fbe9b-798a-4d55-ad49-6ad28cdae7f2
  tls: false
  adminkeySecret: bux-keys
  pubkey: bux_xpub
  prvkey: bux_xprv
