bux-server:
  enabled: true
  ingressControllers:
    - alb

pulse:
  enabled: true
  ingressControllers:
    - alb

bux-console:
  enabled: true
  ingressControllers:
    - alb

bux-wallet:
  enabled: true
  ingressControllers:
    - alb

global:
  domainName: domain.name
  certificate_arn: arn:aws:acm:eu-central-1:123612527616:certificate/f34a3ac5-9832-4b62-9619-b484d9a95951
  tls: false
  adminkeySecret: bux-keys
  pubkey: bux_xpub
  prvkey: bux_xprv
