apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pulse
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
type: Opaque
data:
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "pulse-auth-token") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    {{- $token := (get $secretData "pulse-auth-token") | default (randAlphaNum 32 | b64enc) }}
    pulse-auth-token: {{ $token | quote }}