apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-wallet-frontend.name" . }}-env-configs
  labels:
    {{- include "bux-wallet-frontend.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      "apiUrl": "https://bux-wallet-backend.{{ .Values.global.domainName }}",
      "paymailDomain": "{{ .Values.global.domainName }}"
    }