apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-console.name" . }}-env
  labels:
    {{- include "bux-console.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      "serverUrl": "https://bux.{{ .Values.global.domainName }}/v1",
      "hideServerUrl": false
    }