apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-server.name" . }}-env-configs
  labels:
    {{- include "bux-server.labels" . | nindent 4 }}
data:
  development.json: |-
    {{- (tpl ($.Files.Get "config/development.json" ) .) | nindent 6 -}}