apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-server.name" . }}-env-configs
  labels:
    {{  include "bux-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    auth:
      require_signing: {{ .Values.config.auth.require_signing }}
      scheme: {{ .Values.config.auth.scheme }} 
      signing_disabled: {{ .Values.config.auth.signing_disabled }}
    cache:
      cluster:
        coordinator: {{ .Values.config.cache.cluster.coordinator }} 
        prefix: {{ .Values.config.cache.cluster.prefix }} 
        redis: {{ .Values.config.cache.cluster.redis }} 
      engine: {{ .Values.config.cache.engine }} 
      {{  with .Values.config.cache.redis }}
      redis:
        {{  toYaml . | nindent 6 }}
      {{  end }}    
        url: "redis://{{  .Release.Name}}-redis-master:6379"
    db:
      datastore:
        debug: {{  .Values.config.db.datastore.debug }} 
        engine: {{  .Values.config.db.datastore.engine }} 
        table_prefix: {{  .Values.config.db.datastore.table_prefix }} 
    {{  with .Values.config.db.sql }}
    sql:
      {{  toYaml . | nindent 6 }}
    {{  end }}
        host: "{{  .Release.Name}}-postgresql-server"
    debug: {{ .Values.config.debug }}
    debug_profiling: {{ .Values.config.debug_profiling }}
    disable_itc: {{  .Values.config.graphql.enabled }}
    graphql:
      enabled: {{  .Values.config.graphql.enabled }}
    {{  with .Values.config.nodes }}
    nodes:
      {{  toYaml . | nindent 6 }}
    {{  end }}
    {{  with .Values.config.paymail }}
    paymail:
      {{  toYaml . | nindent 6 }}
    {{  end }}
      default_from_paymail: bux@{{  .Release.Name}}-server.{{  .Values.global.domainName }}
      domains:
        - "{{  .Release.Name}}-server.{{  .Values.global.domainName }}"
    request_logging: {{  .Values.config.request_logging }}
    {{  with .Values.config.server_config }}
    server_config:
      {{  toYaml . | nindent 6 }}
    {{  end }}    
    task_manager:
      factory: {{  .Values.config.task_manager.factory }}
