apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-wallet-backend.name" . }}-env
  labels:
    {{- include "bux-wallet-backend.labels" . | nindent 4 }}
data:
  DB_HOST: 'bux-postgresql'
  BUX_SERVER_URL: 'http://bux-server/v1'
  HTTP_SERVER_CORS_ALLOWEDDOMAINS: 'https://bux-wallet.{{ .Values.global.domainName }}'
  BUX_PAYMAIL_DOMAIN: '{{- .Release.Name}}-server.{{ .Values.global.domainName }}'