apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-wallet-backend.name" . }}-env
  labels:
    {{- include "bux-wallet-backend.labels" . | nindent 4 }}
data:
  DB_HOST: 'bux-postgresql'
  BUX_ADMIN_XPRIV: 'xprv9s21ZrQH143K3CbJXirfrtpLvhT3Vgusdo8coBritQ3rcS7Jy7sxWhatuxG5h2y1Cqj8FKmPp69536gmjYRpfga2MJdsGyBsnB12E19CESK'
  BUX_SERVER_URL: 'http://bux-server:3003/v1'
  HTTP_SERVER_CORS_ALLOWEDDOMAINS: 'https://bux-wallet.{{ .Values.global.domainName }}'
  BUX_PAYMAIL_DOMAIN: '{{ .Values.global.domainName }}'